FROM node:20-alpine3.17 as build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html